# Generated by Django 5.2.7 on 2025-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ManyToManyField(blank=True, to='lesson.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='chapter',
            field=models.ManyToManyField(blank=True, to='lesson.chapter'),
        ),
    ]
