# Generated by Django 5.2.7 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/static/about_us_images/'),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='project/static/about_us_videos/'),
        ),
    ]
